CREATE OR REPLACE VIEW STAGING.LINKEDINVIEW(
	USER_ID,
	TOTAL_ORDERS,
	TOTAL_AMOUNT
)
AS SELECT
	USER_ID::NUMBER(38,0),
	TOTAL_ORDERS::NUMBER(38,0),
	TOTAL_AMOUNT::NUMBER(10,2)
FROM ANALYTICS.USER_METRICS;
        