CREATE OR REPLACE VIEW STAGING.LINKEDINVIEW(
	USER_ID,
	TOTAL_ORDERS,
	TOTAL_AMOUNT
)
AS SELECT
	COALESCE(USER_ID,999)::NUMBER(38,0) AS USER_ID,
	TOTAL_ORDERS::VARCHAR,
	TOTAL_AMOUNT::NUMBER(10,2)
FROM ANALYTICS.USER_METRICS;
        