CREATE OR REPLACE VIEW ANALYTICS.JOINDEVIEW(
	ID,
	TEST,
	T2_ID
)
AS SELECT
	COALESCE(T1.ID,'NA')::NUMBER(38,0) AS ID,
	T1.TEST::VARCHAR(16777216) AS TEST,
	T2.ID::NUMBER(38,0) AS T2_ID
FROM ANALYTICS.NEWIDE T1
LEFT JOIN ANALYTICS.DEPLOYMODIF T2 ON T2.ID = T1.ID;
        