CREATE OR REPLACE DYNAMIC TABLE STAGING.LINKEDINDT
TARGET_LAG = '1 minute'
WAREHOUSE = COMPUTE_WH
(
	ORDER_ID,
	USER_ID,
	AMOUNT,
	ORDER_DATE
)
AS SELECT
	ORDER_ID::NUMBER(38,0),
	USER_ID::NUMBER(38,0),
	AMOUNT::NUMBER(10,2),
	ORDER_DATE::DATE
FROM RAW.ORDERS_RAW;