CREATE OR REPLACE DYNAMIC TABLE ANALYTICS.DT_JOINTEST
TARGET_LAG = '1 minute'
WAREHOUSE = COMPUTE_WH
(
	ID,
	USER_ID,
	TOTAL_ORDERS,
	TOTAL_AMOUNT
)
AS SELECT
	T1.ID::NUMBER(38,0) AS ID,
	T2.USER_ID::NUMBER(38,0) AS USER_ID,
	T2.TOTAL_ORDERS::NUMBER(38,0) AS TOTAL_ORDERS,
	T2.TOTAL_AMOUNT::NUMBER(10,2) AS TOTAL_AMOUNT
FROM ANALYTICS.DEPLOYMODIF T1
LEFT JOIN ANALYTICS.USER_METRICS T2 ON T1.ID = T2.USER_ID;