CREATE OR REPLACE DYNAMIC TABLE ANALYTICS.LINKEDINDT
TARGET_LAG = '1 minute'
WAREHOUSE = COMPUTE_WH
(
	USER_ID,
	NAME,
	CREATED_AT
)
AS SELECT
	USER_ID::NUMBER(38,0),
	NAME::VARCHAR(16777216),
	CREATED_AT::TIMESTAMP_NTZ(9)
FROM RAW.USERS_RAW;